#include "defines.h"
#include "../include/moves.h"

const u16 gTMHMMoves[NUM_TMSHMS] =
{
	MOVE_FOCUSPUNCH,		//1
	MOVE_DRAGONCLAW,		//2
	MOVE_WATERPULSE,		//3
	MOVE_CALMMIND,			//4
	MOVE_DRAININGKISS,		//5
	MOVE_TOXIC,				//6
	MOVE_HAIL,				//7
	MOVE_BULKUP,			//8
	MOVE_BULLETSEED,		//9
	MOVE_HIDDENPOWER,		//10
	MOVE_SUNNYDAY,			//11
	MOVE_TAUNT,				//12
	MOVE_ICEBEAM,			//13
	MOVE_PINMISSILE,		//14
	MOVE_CHARM,				//15
	MOVE_LIGHTSCREEN,		//16
	MOVE_PROTECT,			//17
	MOVE_RAINDANCE,			//18
	MOVE_GIGADRAIN,			//19
	MOVE_SAFEGUARD,			//20
	MOVE_COVET,				//21
	MOVE_SOLARBEAM,			//22
	MOVE_BODYSLAM,			//23
	MOVE_THUNDERBOLT,		//24
	MOVE_PSYSHOCK,			//25
	MOVE_EARTHQUAKE,		//26
	MOVE_RETURN,			//27
	MOVE_DIG,				//28
	MOVE_PSYCHIC,			//29
	MOVE_SHADOWBALL,		//30
	MOVE_BRICKBREAK,		//31
	MOVE_SWIFT,				//32
	MOVE_REFLECT,			//33
	MOVE_SHOCKWAVE,			//34
	MOVE_FLAMETHROWER,		//35
	MOVE_SLUDGEBOMB,		//36
	MOVE_SANDSTORM,			//37
	MOVE_BATONPASS,			//38
	MOVE_ROCKTOMB,			//39
	MOVE_AERIALACE,			//40
	MOVE_OUTRAGE,			//41
	MOVE_FACADE,			//42
	MOVE_FLAMECHARGE,		//43
	MOVE_REST,				//44
	MOVE_WEATHERBALL,		//45
	MOVE_THIEF,				//46
	MOVE_STEELWING,			//47
	MOVE_ROUND,				//48
	MOVE_SCALD,				//49
	MOVE_OVERHEAT,			//50
	MOVE_ROOST,				//51
	MOVE_FOCUSBLAST,		//52
	MOVE_ENERGYBALL,		//53
	MOVE_FALSESWIPE,		//54
	MOVE_FLAREBLITZ,		//55
	MOVE_FLING,				//56
	MOVE_CHARGEBEAM,		//57
	MOVE_MUDSHOT,			//58
	MOVE_ZENHEADBUTT,		//59
	MOVE_BUGBUZZ,			//60
	MOVE_WILLOWISP,			//61
	MOVE_ACROBATICS,		//62
	MOVE_ICYWIND,			//63
	MOVE_EXPLOSION,			//64
	MOVE_SHADOWCLAW,		//65
	MOVE_PAYBACK,			//66
	MOVE_EARTHPOWER,		//67
	MOVE_PSYCHOCUT,			//68
	MOVE_ROCKPOLISH,		//69
	MOVE_FLASHCANNON,		//70
	MOVE_SEEDBOMB,			//71
	MOVE_VOLTSWITCH,		//72
	MOVE_THUNDERWAVE,		//73
	MOVE_VENOSHOCK,			//74
	MOVE_AVALANCHE,			//75
	MOVE_STEALTHROCK,		//76
	MOVE_HEX,				//77
	MOVE_PLAYROUGH,			//78
	MOVE_DARKPULSE,			//79
	MOVE_ROCKSLIDE,			//80
	MOVE_IRONHEAD,			//81
	MOVE_THROATCHOP,		//82
	MOVE_WORKUP,			//83
	MOVE_POISONJAB,			//84
	MOVE_SNARL,				//85
	MOVE_PHANTOMFORCE,		//86
	MOVE_SWAGGER,			//87
	MOVE_SLEEPTALK,			//88
	MOVE_UTURN,				//89
	MOVE_SPIKES,			//90
	MOVE_TOXICSPIKES,		//91
	MOVE_TRICKROOM,			//92
	MOVE_WILDCHARGE,		//93
	MOVE_LEECHLIFE,			//94
	MOVE_AIRSLASH,			//95
	MOVE_SCALESHOT,			//96
	MOVE_DEFOG,				//97
	MOVE_KNOCKOFF,			//98
	MOVE_DAZZLINGGLEAM,		//99
	#ifdef MOVE_ICESPINNER
	MOVE_ICESPINNER,		//100
	#else
	MOVE_ICICLECRASH,		//100
	#endif
	MOVE_POWERGEM,			//101
	MOVE_GUNKSHOT,			//102
	MOVE_SYNTHESIS,			//103
	MOVE_IRONDEFENSE,		//104
	MOVE_ELECTRICTERRAIN,	//105
	MOVE_GRASSYTERRAIN,		//106
	MOVE_MISTYTERRAIN,		//107
	MOVE_PSYCHICTERRAIN,	//108
	MOVE_TERRAINPULSE,		//109
	MOVE_SOLARBLADE,		//110
	#ifdef MOVE_CHILLINGWATER
	MOVE_CHILLINGWATER,		//111
	#else
	MOVE_BUBBLEBEAM,		//111
	#endif
	MOVE_AURASPHERE,		//112
	MOVE_AQUATAIL,			//113
	MOVE_STEELBEAM,			//114
	MOVE_DRAGONPULSE,		//115
	MOVE_SIGNALBEAM,		//116
	MOVE_HYPERVOICE,		//117
	MOVE_METEORBEAM,		//118
	MOVE_AURORAVEIL,		//119
	MOVE_FLIPTURN,			//120
	MOVE_CUT,				//121
	MOVE_FLY,				//122
	MOVE_SURF,				//123
	MOVE_STRENGTH,			//124
	MOVE_FLASH,				//125
	MOVE_ROCKSMASH,			//126
	MOVE_WATERFALL,			//127
	MOVE_ROCKCLIMB,			//128
};

const u16 gMoveTutorMoves[NUM_MOVE_TUTOR_MOVES] =
{
	// Badge 0
	MOVE_HELPINGHAND,		//1
	MOVE_METRONOME,			//2
	MOVE_LASERFOCUS,		//3
	MOVE_PSYCHUP,			//4
	MOVE_HEALBELL,			//5
	MOVE_BLOCK,				//6
	MOVE_INFESTATION,		//7
	MOVE_BUGBITE,			//8
	MOVE_MAGNETRISE,		//9
	MOVE_NIGHTSHADE,		//10
	MOVE_FAKETEARS,			//11
	MOVE_HONECLAWS,			//12
	MOVE_SCARYFACE,			//13
	MOVE_SNATCH,			//14
	MOVE_MAGICALLEAF,		//15
	MOVE_DISARMINGVOICE,	//16

	// Badge 1
	MOVE_PLUCK,				//17
	MOVE_AIRCUTTER,			//18
	MOVE_BULLDOZE,			//19
	MOVE_LOWSWEEP,			//20
	MOVE_BRUTALSWING,		//21
	MOVE_ACIDSPRAY,			//22
	#ifdef MOVE_TRAILBLAZE	
	MOVE_TRAILBLAZE,		//23
	#else
	MOVE_NEEDLEARM,			//23
	#endif
	#ifdef MOVE_POUNCE
	MOVE_POUNCE,			//24
	#else
	MOVE_LUNGE,				//24
	#endif
	MOVE_INCINERATE,		//25
	MOVE_BRINE,				//26
	MOVE_ELECTROWEB,		//27
	MOVE_ECHOEDVOICE,		//28
	MOVE_STRUGGLEBUG,		//29
	MOVE_ATTRACT,			//30
	MOVE_UPROAR,			//31
	MOVE_TRICK,				//32

	// Badge 2
	MOVE_FIREFANG,			//33
	MOVE_ICEFANG,			//34
	MOVE_THUNDERFANG,		//35
	MOVE_DRAGONTAIL,		//36
	MOVE_POISONTAIL,		//37
	MOVE_DUALWINGBEAT,		//38
	MOVE_BOUNCE,			//39
	MOVE_RECYCLE,			//40
	MOVE_SKILLSWAP,			//41
	MOVE_MAGICCOAT,			//42
	MOVE_AGILITY,			//43
	MOVE_SECRETPOWER,		//44
	MOVE_NATUREPOWER,		//45
	MOVE_WHIRLPOOL,			//46
	MOVE_DREAMEATER,		//47
	MOVE_SILVERWIND,		//48

	// Badge 3
	MOVE_BLAZEKICK,			//49
	MOVE_MUDDYWATER,		//50
	MOVE_ICICLESPEAR,		//51
	MOVE_SMACKDOWN,			//52
	MOVE_SKYDROP,			//53
	MOVE_BREAKINGSWIPE,		//54
	MOVE_VACUUMWAVE,		//55
	MOVE_TRIATTACK,			//56
	MOVE_GRASSKNOT,			//57
	MOVE_LOWKICK,			//58
	MOVE_HEATCRASH,			//59
	MOVE_TAILWIND,			//60
	MOVE_ROLEPLAY,			//61
	MOVE_ENDURE,			//62
	MOVE_NATURALGIFT,		//63
	MOVE_CORROSIVEGAS,		//64

	// Badge 4
	MOVE_FIREPUNCH, 		//65
	MOVE_ICEPUNCH,			//66
	MOVE_THUNDERPUNCH,		//67
	MOVE_ROCKBLAST,			//68
	MOVE_TRIPLEAXEL,		//69
	MOVE_SMARTSTRIKE,		//70
	MOVE_CRUNCH,			//71
	MOVE_SKITTERSMACK,		//72
	MOVE_DUALCHOP,			//73
	MOVE_GYROBALL,			//74
	MOVE_ELECTROBALL,		//75
	MOVE_IRONTAIL,			//76
	MOVE_STOMPINGTANTRUM,	//77
	MOVE_REVERSAL,			//78
	#ifdef MOVE_TERABLAST
	MOVE_TERABLAST,			//79
	#else
	MOVE_SNORE,				//79
	#endif
	MOVE_STOREDPOWER,		//80

	// Badge 5
	MOVE_BRAVEBIRD,			//81
	MOVE_SKYATTACK,			//82
	MOVE_DRILLRUN,			//83
	MOVE_BURNINGJEALOUSY,	//84
	MOVE_MYSTICALFIRE,		//85
	MOVE_HEATWAVE,			//86
	MOVE_LIQUIDATION,		//87
	MOVE_LASHOUT,			//88
	MOVE_RETALIATE,			//89
	MOVE_LEAFBLADE,			//90
	MOVE_PSYCHICFANGS,		//91
	MOVE_HYPERBEAM,			//92
	MOVE_GIGAIMPACT,		//93
	MOVE_SLUDGEWAVE,		//94
	MOVE_CROSSPOISON,		//95
	MOVE_XSCISSOR,			//96

	// Badge 6
	MOVE_GRASSPLEDGE,		//97
	MOVE_WATERPLEDGE,		//98
	MOVE_FIREPLEDGE,		//99
	MOVE_SCORCHINGSANDS,	//100
	MOVE_POLLENPUFF,		//101
	MOVE_EXTRASENSORY,		//102
	MOVE_HIGHHORSEPOWER,	//103
	MOVE_TAILSLAP,			//104
	MOVE_POLTERGEIST,		//105
	MOVE_GRASSYGLIDE,		//106
	MOVE_POWERWHIP,			//107
	MOVE_FOULPLAY,			//108
	MOVE_DARKESTLARIAT,		//109
	MOVE_BODYPRESS,			//110
	MOVE_ENDEAVOR,			//111
	MOVE_ENCORE,			//112

	// Badge 7
	MOVE_SWORDSDANCE, 		//113
	MOVE_NASTYPLOT,			//114
	MOVE_FIREBLAST,			//115
	MOVE_HYDROPUMP,			//116
	MOVE_LEAFSTORM,			//117
	MOVE_THUNDER,			//118
	MOVE_BLIZZARD,			//119
	MOVE_HURRICANE,			//120
	MOVE_DRAINPUNCH,		//121
	MOVE_SUPERPOWER,		//122
	MOVE_HEAVYSLAM,			//123
	MOVE_MEGAHORN,			//124
	MOVE_STONEEDGE,			//125
	MOVE_SUPERFANG,			//126
	MOVE_PAINSPLIT,			//127
	MOVE_SUBSTITUTE,		//128

	// Badge 8
	MOVE_FRENZYPLANT,		//129
	MOVE_BLASTBURN,			//130
	MOVE_HYDROCANNON,		//131
	MOVE_DRACOMETEOR,		//132
	MOVE_CLOSECOMBAT,		//133
	MOVE_EXPANDINGFORCE,	//134
	MOVE_MISTYEXPLOSION,	//135
	MOVE_RISINGVOLTAGE,		//136
	MOVE_STEELROLLER,		//137
	MOVE_DOUBLETEAM,		//138
	MOVE_DRAGONDANCE,		//139
	MOVE_GRAVITY,			//140
	MOVE_MAGICROOM,			//141
	MOVE_WONDERROOM,		//142
	MOVE_POWERUPPUNCH,		//143
	MOVE_LASTRESORT,		//144
	
};
